# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "RNAdMob.xcodeproj")
    get_certificates( # Create or get certificate, and install it
      output_path: "./builds"
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",
      filename: "provisioning.mobileprovision"
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "RNAdMob.xcodeproj", # Place here your project name
      target_filter: "RNAdMob", # Here too
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Release"
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )
    build_app(workspace: "RNAdMob.xcworkspace", scheme: "RNAdMob")
    upload_to_testflight
  end
end
